version: 2.0

jobs:
  build:
    docker:
      - image: openwrtorg/sdk:x86-64
    environment:
      - CI_PROJECT_DIR: "~/project"
    steps:
      - checkout
      - run:
          name: build firewall3
          command: bash -x .circleci/build.sh
      - store_artifacts:
          path: ~/sdk/bin/packages/x86_64/base/firewall*
      - persist_to_workspace:
          root: ~/sdk/bin/packages/x86_64/base/
          paths:
            - firewall*
  test:
    docker:
      - image: openwrtorg/rootfs:x86-64
        command: "/sbin/init"
    steps:
      - run:
          name: install CI requirements
          command: |
            opkg update
            opkg install ca-certificates ca-bundle tar git
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: install firewall3
          command: |
            opkg update
            opkg install --force-reinstall /tmp/workspace/firewall*
            opkg install python3-pip
            python3 -m pip install pytest
      - checkout
      - run:
          name: test firewall3
          command: |
            ls
            python3 -m pytest

workflows:
  version: 2
  build-n-test:
    jobs:
      - build
      - test:
          requires:
            - build
